#-----------------------------------------------------------------------------#
#
# Top level tests
#
#-----------------------------------------------------------------------------#
CompileAll:
  script:
    - export C_INCLUDE_PATH=/nix/store/kxxkzfqrv37fv3szrh2p6nga50rnpg2a-riscv32-unknown-elf-rv32imac-toolchain-8.3.0-afcc8bc/riscv32-unknown-elf/include
    - nix-shell /var/lib/gitlab-runner/shell.nix --run './compile_all.sh'
    - unset C_INCLUDE_PATH
  tags: ["freertos"]